name: droste
dependencies:
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- freetype
- ipykernel=4.3.1=py35_0
- ipython=5.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.1.0=py35_0
- libsodium
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune
- mkl
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numpy=1.11.1=py35_0
- openssl
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- patsy=0.4.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyzmq
- qt
- qtconsole=4.2.1=py35_0
- requests=2.10.0=py35_0
- scikit-learn=0.17.1=np111py35_2
- scipy=0.17.1=np111py35_1
- seaborn=0.7.0=py35_0
- setuptools=25.1.6=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite
- statsmodels=0.6.1=np111py35_1
- tk
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xlrd
- zeromq
- zlib
- pip:
  - colorlover==0.2.1
  - cufflinks==0.8.2
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - jupyterlab==0.1.1
  - plotly==1.12.4
  - prompt-toolkit==1.0.3
  - qgrid==0.3.2
  - tqdm==4.7.6
  - widgetsnbextension==1.2.6
  - xgboost==0.6a2
